config/routes.rb
Kyoiku::Application.routes.draw do

  resources :tyokyos do
    member do
    end

    collection do
      get "tweet_tyokyo"
    end
  end

end

app/models/tyokyo.rb
class Tyokyo < ActiveRecord::Base
  attr_accessible :after, :before
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tyokyos_controller.rb
class TyokyosController < ApplicationController
  # GET /tyokyos
  # GET /tyokyos.json
  def index
    @tyokyos = Tyokyo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tyokyos }
    end
  end

  # GET /tyokyos/1
  # GET /tyokyos/1.json
  def show
    @tyokyo = Tyokyo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tyokyo }
    end
  end

  # GET /tyokyos/new
  # GET /tyokyos/new.json
  def new
    @tyokyo = Tyokyo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tyokyo }
    end
  end

  # GET /tyokyos/1/edit
  def edit
    @tyokyo = Tyokyo.find(params[:id])
  end

  # POST /tyokyos
  # POST /tyokyos.json
  def create
    @tyokyo = Tyokyo.new(params[:tyokyo])

    respond_to do |format|
      if @tyokyo.save
        format.html { redirect_to @tyokyo, :notice => 'Tyokyo was successfully created.' }
        format.json { render :json => @tyokyo, :status => :created, :location => @tyokyo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tyokyo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tyokyos/1
  # PUT /tyokyos/1.json
  def update
    @tyokyo = Tyokyo.find(params[:id])

    respond_to do |format|
      if @tyokyo.update_attributes(params[:tyokyo])
        format.html { redirect_to @tyokyo, :notice => 'Tyokyo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tyokyo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tyokyos/1
  # DELETE /tyokyos/1.json
  def destroy
    @tyokyo = Tyokyo.find(params[:id])
    @tyokyo.destroy

    respond_to do |format|
      format.html { redirect_to tyokyos_url }
      format.json { head :no_content }
    end
  end

  def tweet_tyokyo
    require 'rubygems'
    require "twitter"

    Twitter.configure do |cnf|
      cnf.consumer_key = "kFAJrOKDWDH7nRVC5XBO2A"
      cnf.consumer_secret = "EcGevWB37RRWJ7icLYpEmMOShgMIatHF2EjQQA6N1w"
      cnf.oauth_token = "1287046849-gf3LBk9wIh297961rtnYjCxoX9hZEzrgFzamN8C"
      cnf.oauth_token_secret = "t7NDNy1qXutDwFTKnBby9kIibK89XVA6S1baX8GVII"
    end

    # @msg = "Heloo World2"
    @tyokyos = Tyokyo.all

    select_index = rand(@tyokyos.length);
    @tyokyos.each_with_index do |tyokyo,i|
      if i == select_index then
        @msg_before = tyokyo.before
        @msg_after = tyokyo.after
      end
    end

    # # ここからテスト
    # @msg_before = "test"
    # @msg_after = "tweet"

    Twitter.update(@msg_before+" : "+@msg_after)


    respond_to do |format|
      format.html { render :action => "tweet_tyokyo" }
      format.json { render :json => @msg_before, :json => @msg_after }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tyokyos_helper.rb
module TyokyosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kyoiku</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tyokyos/_form.html.erb
<%= form_for(@tyokyo) do |f| %>
  <% if @tyokyo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tyokyo.errors.count, "error") %> prohibited this tyokyo from being saved:</h2>

      <ul>
      <% @tyokyo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :before %><br />
    <%= f.text_field :before %>
  </div>
  <div class="field">
    <%= f.label :after %><br />
    <%= f.text_field :after %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tyokyos/edit.html.erb
<h1>Editing tyokyo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tyokyo %> |
<%= link_to 'Back', tyokyos_path %>

app/views/tyokyos/index.html.erb
<h1>Listing tyokyos</h1>

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tyokyos.each do |tyokyo| %>
  <tr>
    <td><%= tyokyo.before %></td>
    <td><%= tyokyo.after %></td>
    <td><%= link_to 'Show', tyokyo %></td>
    <td><%= link_to 'Edit', edit_tyokyo_path(tyokyo) %></td>
    <td><%= link_to 'Destroy', tyokyo, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tyokyo', new_tyokyo_path %>

app/views/tyokyos/new.html.erb
<h1>New tyokyo</h1>

<%= render 'form' %>

<%= link_to 'Back', tyokyos_path %>

app/views/tyokyos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Before:</b>
  <%= @tyokyo.before %>
</p>

<p>
  <b>After:</b>
  <%= @tyokyo.after %>
</p>


<%= link_to 'Edit', edit_tyokyo_path(@tyokyo) %> |
<%= link_to 'Back', tyokyos_path %>

app/views/tyokyos/tweet_tyokyo.html.erb
before: <%= @msg_before %></br>
after: <%= @msg_after%>